### PR TITLE
Parse rename/reschedule/extend/change

### LINKED ISSUE #99: Parse reschedule and rename command
* `rename [TASK/EVENT NUMBER] to [NEW TASK/EVENT NAME]` Example: `rename d3 to sell eggs`
* `reschedule [TASK NUMBER] to [DATE] [TIME]` Example: `reschedule d3 to 6pm`
* `reschedule [EVENT NUMBER] to [DATE] [TIME]` Example: `reschedule e6 to 5pm` (change start time to 5pm and keeps event duration)
* `reschedule [EVENT NUMBER] to until [DATE] [TIME]` Example: `reschedule e6 to 5pm` (change end time to 5pm)
* `reschedule [EVENT NUMBER] to [DATE] [TIME] to [DATE] [TIME]` Example: `reschedule e6 to 5pm to 7pm` (change start time to 5pm and end time to 7pm)

@cs2103jan2016-v15-1j/developers

### PR DESCRIPTION
**Pull request by tran-tien-dat**
closes #99 @cs2103jan2016-v15-1j/developers please comment
My proposal for the syntax:
* `rename d2 to do more maths`: rename deadline task `d2` to `do more maths`
* `reschedule e1 to 1.00 pm`: change starting time of event `e1` to 1.00 pm on the original date, keep the original duration
* `reschedule f1 to Sunday`: change floating task `f1` to a deadline task and set the deadline at 23.59 on Sunday
* `extend e3 to 7 pm`: change the ending time of event `e3` to 7 pm on the original date, keep original starting time

Note that `rename` and `reschedule` can be replaced by simply `change`

### CODE REVIEW

**Comment by shaunthium** [comment]
Is there an option to set new start and end time at the same time?

**Comment by tran-tien-dat** [comment]
@shaunthium what do you suggest?

**Comment by tran-tien-dat** [comment]
@shaunthium please take a look at `ChangeCommand`. Do you agree with this way of storing the information? (You will need to use them to implement `ChangeCommand.execute()`

**Comment by shaunthium** [comment]
Yes it looks good

**Pull request merged**
